gather_blog_context:
  description: >
    Perform in-depth research on the topic: {topic}, tailored to the desired tone: {tone}.
    Use Tools to collect up-to-date insights, news developments, keyword suggestions, expert quotes, and supporting data.
    Your goal is to build a rich, current, and SEO-friendly knowledge base that will guide content generation.
  expected_output: >
    - 10 concise bullet points with key facts or insights
    - A short summary of recent news and relevant trends
    - 2-3 credible references with source links
    - A brief paragraph suggesting a compelling angle or narrative direction for the blog
  agent: context_collector

write_blog_content:
  description: >
    Based on the research provided, generate a complete blog post about: {topic}, using a {tone} tone.
    Write a compelling title, introduction, several structured sections (from key insights), and a strong conclusion.
    Leverage the word search tool to enhance SEO and vocabulary.
    For the exporter provide metadata including title, description, keywords, and suggested URL slug for export. don't include this in the blog post.
    Ensure the content is well-structured, engaging, and optimized for search engines.
  expected_output: >
    - A full blog post with Markdown structure (title, H2 sections, intro, conclusion)
    - Optimized language using relevant keywords and tone
    - Metadata dictionary with title, meta-description, keywords, and slug
  agent: content_creator

finalize_and_export:
  description: >
    Format the blog content received from the content creator into clean Markdown.
    Ensure the writing flows smoothly, integrates SEO terms, and meets quality standards.
    Export the blog as a Markdown file and the SEO metadata as a JSON string for easy publishing.
  expected_output: >
    - Final Markdown-formatted blog post as a string
    - JSON-formatted metadata string with keys: title, description, keywords, slug
  agent: exporter
